services:
  artificial-authorship-verification:
    image: registry.webis.de/code-teaching/theses/artificial-authorship-verification
    platform: linux/amd64
    build: .
    volumes:
      - ./:/src/
  mongodb:
      image: mongo:8
      restart: unless-stopped
      ports:
        - "27017:27017"         # publish container port to host
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        SAIA_KEY: ${SAIA_KEY}
      volumes:
        - mongo-data:/data/db # persistent storage of DB data; data survives container recreation
volumes:
  mongo-data: # docker maps container's /data/db to this volume