[tool.poetry]
name = "artificial-authorship-verification"
version = "0.1.0"
description = "Authorship Verification Research Code"
authors = ["Klara M. Gutekunst <klara.gutekunst@uni-kassel.de>", "Janek Bevendorff <janek.bevendorff@uni-weimar.de>"]
readme = "README.md"
packages = [
    { include = "genai_detection" },
]

[tool.poetry.dependencies]
datasets = "^4.0.0"
python-dotenv = "^1.1.1"
pathlib = "^1.0.1"
matplotlib = "^3.10.3"
beautifulsoup4 = "^4.13.4"
pydantic = "^2.11.7"
python = ">=3.10,<3.13"
numpy = "^1.26.4"
scipy = "^1.14.1"
transformers = "^4.53.3"
accelerate = "^1.2.1"
peft = "^0.14.0"
click = "^8.1.7"
tqdm = {extras = ["notebook"], version = "^4.67.1"}
scikit-learn = "^1.6.1"
google-cloud-aiplatform = "^1.77.0"
openai = "^1.59.8"
pyppmd = "^1.1.1"
skops = "^0.11.0"
xgboost = "^2.1.3"
seaborn = {extras = ["stats"], version = "^0.13.2"}
pandas = "^2.1.3"
parallel-pandas = "^0.6.5"
pymongo = "^4.15.3"
notebook = "^7.4.2"
more-itertools = "^10.7.0"
serpapi = "^0.1.5"
spacy = "^3.8.7"
dotenv = "^0.9.9"
cmake = "3.31.6"
tokenizers= ">=0.21,<0.22"
sentencepiece = "^0.2.0"
evaluate = "^0.4.3"
bert-score = "^0.3.13"
nltk = "^3.9.1"
rouge-score = "^0.1.2"
word-mover-distance = "^0.0.3"
gensim = "^4.3.3"
dirtyjson = "^1.0.8"
sentence-transformers = "^5.0.0"
openpyxl = "^3.1.5"
unilm = {git = "https://github.com/Liadrinz/transformers-unilm.git"}
llmdet = {git = "https://github.com/TrustedLLM/LLMDet.git"}
pyreadstat = "^1.3.0"
chardet = "^5.2.0"
deepl = "^1.22.0"
torch = { version = "^2.5.0", source = "pypi" }
torchvision = { version = "^0.20.0", source = "pypi" }
torchaudio = { version = "^2.5.0", source = "pypi" }
dspy = "^3.0.3"
resiliparse = "^0.15.2"
ray = "^2.53.0"
black = "^26.1.0"
mlstatkit = "^0.1.91"
pingouin = "^0.6.1"
langdetect = "^1.0.9"

[[tool.poetry.source]]
name = "torch-cu128"
url = "https://download.pytorch.org/whl/cu128"
priority = "explicit"

[[tool.poetry.source]]
name = "torch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
genai-detection = 'genai_detection.cli.main:main'
