import logging
import os
from pathlib import Path
from typing import Optional, List, Dict

from bson import ObjectId
from pymongo import MongoClient
from pymongo.errors import PyMongoError

from genai_detection.config import CONFIG

PROJECT_ROOT = Path(__file__).resolve().parents[2]

logger = logging.getLogger(__name__)

class ParaphraseMongoDB:

    def __init__(self, local_ray=True):
        if local_ray:
            # Local (via local ray instance)
            self.mongodb_uri = f"mongodb://{CONFIG.MONGO_USER}:{CONFIG.MONGO_PASSWORD}@{CONFIG.MONGO_HOST}:{CONFIG.MONGO_PORT}/"
            # uri = f"mongodb://{CONFIG.MONGO_USER}:{CONFIG.MONGO_PASSWORD}@{CONFIG.MONGO_HOST}:{CONFIG.MONGO_PORT}/"
        else:
            # Ray on betaweb server
            self.mongodb_uri = f"mongodb://{os.environ['MONGO_USER']}:{os.environ['MONGO_PASSWORD']}@artificial-authorship-verification-mongodb.webisservices.svc.cluster.local:27017/"

        self.client = MongoClient(self.mongodb_uri)
        try:
            self.client.admin.command("ping")
            logging.info("Successfully connected as MongoDB root user!")
        except Exception as e:
            logging.warning("Connection failed: %s", e)
            raise e

        self.db = self.client[CONFIG.MONGO_DATABASE or "impostors"]
        self.original_collection = self.db[
            CONFIG.MONGO_ORIGINAL_TEXT_COLLECTION or "original_text"
        ]

        # Create collections if they don't exist
        for collection_name in [
            CONFIG.MONGO_PARAPHRASE_COLLECTION,
            CONFIG.MONGO_PARAPHRASE_SCORE_COLLECTION,
            CONFIG.MONGO_IMPOSTOR_OUTPUT_COLLECTION,
            CONFIG.MONGO_ON_THE_FLY_COLLECTION,
            CONFIG.MONGO_TRANSLATION_COLLECTION,
            CONFIG.MONGO_NAIVE_PARAPHRASE_COLLECTION,
            CONFIG.MONGO_TEST_PAIRS_COLLECTION,
            CONFIG.MONGO_TRAIN_PAIRS_COLLECTION,
            CONFIG.MONGO_ALL_PAIRS_COLLECTION,
            CONFIG.MONGO_SUP_BASELINE_CONFIG_PREDS

        ]:
            if collection_name not in self.db.list_collection_names():
                self.db.create_collection(collection_name)
                logging.info(f"Created collection: {collection_name}")
            else:
                logging.info(
                    f"Collection '{collection_name}' already exists. Skipping creation."
                )

        self.non_naive_paraphrase_collection = self.db[CONFIG.MONGO_PARAPHRASE_COLLECTION]    # two-step/ non-naive llm
        # paraphrases
        self.on_the_fly_collection = self.db[CONFIG.MONGO_ON_THE_FLY_COLLECTION] # on-the-fly impostors
        self.translation_collection = self.db[CONFIG.MONGO_TRANSLATION_COLLECTION] # paraphrases generated by
        # translation
        self.naive_paraphrase_collection = self.db[CONFIG.MONGO_NAIVE_PARAPHRASE_COLLECTION]    # one-step/
        # naive llm paraphrases
        self.paraphrase_score_collection = self.db[CONFIG.MONGO_PARAPHRASE_SCORE_COLLECTION]  # paraphrase scores
        self.impostor_output_collection = self.db[CONFIG.MONGO_IMPOSTOR_OUTPUT_COLLECTION]  # output of impostor
        # approach
        self.test_pairs_collection = self.db[CONFIG.MONGO_TEST_PAIRS_COLLECTION] # IDs of texts and their ground truth (reproducibility of evaluation)
        self.train_pairs_collection = self.db[CONFIG.MONGO_TRAIN_PAIRS_COLLECTION] # IDs of texts and their ground truth
        self.all_pairs_collection = self.db[CONFIG.MONGO_ALL_PAIRS_COLLECTION]  # merge of train and test pairs
        self.supervised_baseline_diff_config_preds_collection = self.db[CONFIG.MONGO_SUP_BASELINE_CONFIG_PREDS] # predictions of supervised baseline for different configurations
        self.supervised_baseline_diff_config_scores_collection = self.db[CONFIG.MONGO_SUP_BASELINE_CONFIG_SCORES]


    def reset_collection(self, collection_name:str):
        self.db.drop_collection(collection_name)
        logging.info(f"Dropped collection {collection_name}")
        self.db.create_collection(collection_name)
        logging.info(f"Created new collection {collection_name}")
        return self.db[collection_name]

    @staticmethod
    def update_document(collection, _id: str, update_data: dict) -> int:
        """
        Update an entry in the specified collection by its ID.
        If no document with _id exists, no action is taken.
        If update_data contains fields that already exist, they will be overwritten, if fields are non-existent, they will be created.
        :param collection: The MongoDB collection to update.
        :param text_id: The ID of the text document to update.
        :param update_data: A dictionary containing the fields to update.
        :return: The number of documents modified (0 or 1).
        """
        assert isinstance(update_data, dict), "update_data must be a dictionary"
        result = collection.update_one({"_id": _id}, {"$set": update_data})
        return result.modified_count

    @staticmethod
    def insert_document(collection, insert_data: dict):
        """
        Insert an entry in the specified collection.
        :param collection: The MongoDB collection to insert.
        :param insert_data: A dictionary with the data to insert.
        :return: -
        """
        assert isinstance(insert_data, dict), f"insert_data must be a dictionary, but is {type(insert_data)}."
        collection.insert_one(insert_data)

    @staticmethod
    def insert_documents(collection, insert_data: List[dict]):
        """
        Insert an entry in the specified collection.
        :param collection: The MongoDB collection to insert.
        :param insert_data: A dictionary with the data to insert.
        :return: -
        """
        collection.insert_many(insert_data)

    @staticmethod
    def find_document_by_id(collection, document_id: str):
        """
        Find an entry in the specified collection by its text ID.
        :param collection: The MongoDB collection to search.
        :param document_id: The ID of the text document to find.
        :return: The found document as a cursor object, or None if not found.
        """
        document = collection.find({"_id": ObjectId(document_id)})
        return document

    def find_document_by_non_id_field(self, collection, document_field_name: str, document_value:str):
        """
        Find an entry in the specified collection by its value of a non-id field.
        :param collection: The MongoDB collection to search.
        :param document_value: The value of a non-id field.
        :param document_field_name: The name of the non-id field.
        :return: The found document as a cursor object, or None if not found.
        """
        # document = collection.find({document_field_name: document_value})
        return self.find_document_by_multiple_fields(
            collection=collection, search_args={document_field_name: document_value}
        )

    def delete_documents_by_non_id_field(
        self, collection, document_field_name: str, document_value: str
    ) -> int:
        """
        Delete all documents in the specified collection where a non-id field
        matches the given value.

        :param collection: The MongoDB collection to delete from.
        :param document_field_name: The name of the non-id field.
        :param document_value: The value to match.
        :return: Number of documents deleted.
        """
        result = collection.delete_many({document_field_name: document_value})
        return result.deleted_count

    @staticmethod
    def find_document_by_multiple_fields(
        collection, search_args:dict
    ):
        """
        Find an entry in the specified collection by its value of a non-id field.
        :param collection: The MongoDB collection to search.
        :param search_args: The names of the non-id fields and their values of a non-id fields in a dictionary.
        :return: The found document as a cursor object, or None if not found.
        """
        document = collection.find({**search_args}).sort("_id", 1)
        return document

    def get_random_matching_documents_from_collection(self, collection, num_samples: int, search_args:dict):
        """
        Obtain random documents from the MongoDB collection for the given dataset.
        Ensures texts are not identical to the anchor text.

        :param num_samples: Number of impostor samples to retrieve.
        :param collection: The MongoDB collection to search.
        :param search_args: The names of the fields and their values in a dictionary.
        :return: A list of randomly sampled documents.
        """
        pipeline = [
            {"$match": search_args},
            {"$sample": {"size": num_samples}},
        ]

        # Use aggregation to avoid materializing huge collections
        return collection.aggregate(pipeline)

    def get_text_or_id_from_orginal_collection(self, text: Optional[str], text_id: Optional[str]):
        """
        Returns text and text_id from a document in the original collection.
        :param text: input text to generate impostors for (i.e., the candidate text)
        :param text_id: ID in a mongo database containing texts to retrieve impostors from.
        :return: A tuple containing text and text_id (can be none if not yet in collection).
        """
        assert text or text_id, "Either text or text_id must be provided."
        # Get text from mongodb if missing
        if not text:
            # Should only contain one element because _id is the primary key
            text = self.find_document_by_id(
                collection=self.original_collection, document_id=text_id
            )[0]["text"]
            assert (
                (text is not None) and type(text) == str and len(text) > 0
            ), f"Text ID {text_id} not found."
            # logger.info("Obtained text from text ID: %s, length of text %d", text_id, len(text))

        if not text_id:
            text_id = self.find_document_by_non_id_field(collection=self.original_collection, document_field_name="text", document_value=text)[0]["_id"]
            # logger.info("Obtained text ID from text; text ID: %s", text_id)
        # Save text in mongoDB if not yet present
        if text and text_id:
            existing = self.find_document_by_id(
                collection=self.original_collection, document_id=text_id
            )
            if existing is None:
                raise Exception(f"Document ID {text_id} not found.")
                self.mongoDB.insert_document(
                    collection=self.original_collection,
                    insert_data={"text": text},
                )
        return text, text_id

    def get_texts_for_ids(self, text_ids: List[str]) -> List[str]:
        """
        Retrieve texts for a list of IDs from the original collection in bulk in order.
        :param text_ids: List of MongoDB document IDs
        :return: List of texts corresponding to the IDs (in the same order)
        """
        if not text_ids:
            return []
        if isinstance(text_ids[0], str):
            text_ids = [ObjectId(text_id) for text_id in text_ids]

        # Bulk query: _id in text_ids
        cursor = self.original_collection.find(
            {"_id": {"$in": text_ids}},  # $in matches any ID in the list
            {"_id": True, "text": True},  # only return the text field
        )

        # Convert to list of texts, keeping order
        docs = list(cursor)
        id_to_text = {doc["_id"]: doc["text"] for doc in docs}
        texts = [id_to_text[ObjectId(i)] for i in text_ids]

        # Optional sanity check
        if len(texts) != len(text_ids):
            missing = set(text_ids) - {doc["_id"] for doc in cursor}
            logging.warning("Some IDs not found in MongoDB: %s", missing)

        return texts

    def find_paraphrases(self, document_id: str):
        """
        Find an entry in the specified collection by its text ID.
        :param document_id: The ID of the original document. Paraphrases have different _id.
        :return: The found document as a cursor, or None if not found.

        https://www.mongodb.com/docs/manual/reference/method/db.collection.find/ (06.11.2025)
        """
        documents = self.non_naive_paraphrase_collection.find({"text_id": document_id}).sort("_id", 1)
        return documents

    def get_all_data_but_certain_from_original_texts(
        self,
        in_args: Dict[str, str]=None,
        not_in_args: Dict[str, str]=None,
        batch_size: int = 1000,
    ):
        """
        Single-use generator that yields all but pairs containing any of not_in_args with original texts.
    Uses batching to minimize MongoDB round-trips and memory usage.
        """
        try:
            query = {}
            # Include conditions
            if in_args:
                query.update({k: {"$in": v if isinstance(v, list) else [v]} for k, v in in_args.items()})

            # Exclude conditions
            if not_in_args:
                query.update({k: {"$nin": v if isinstance(v, list) else [v]} for k, v in not_in_args.items()})
            projection = {"_id": 0, "left_id": 1, "right_id": 1, "same": 1}
            print(query)
            pairs_cursor = self.all_pairs_collection.find(
                query,
                projection,
                batch_size=batch_size,
            ).sort("_id", 1)

            batch = []

            for pair in pairs_cursor:
                batch.append(pair)

                if len(batch) >= batch_size:
                    yield from self._process_pair_batch(batch)
                    batch.clear()

            # process remaining pairs
            if batch:
                yield from self._process_pair_batch(batch)

        except PyMongoError as e:
            logging.error(f"MongoDB error while fetching documents: {e}")

    def get_training_data_from_original_texts(
        self,
        dataset_name: str,
        batch_size: int = 1000,
    ):
        """
        Single-use generator that yields training pairs with original texts.
        Uses batching to minimize MongoDB round-trips and memory usage.
        """
        try:
            pairs_cursor = self.train_pairs_collection.find(
                {"dataset_name": dataset_name},
                {"_id": 0, "left_id": 1, "right_id": 1, "same": 1},
                batch_size=batch_size,
            ).sort("_id", 1)

            batch = []

            for pair in pairs_cursor:
                batch.append(pair)

                if len(batch) >= batch_size:
                    yield from self._process_pair_batch(batch)
                    batch.clear()

            # process remaining pairs
            if batch:
                yield from self._process_pair_batch(batch)

        except PyMongoError as e:
            logging.error(f"MongoDB error while fetching documents: {e}")
        except Exception as e:
            logging.exception("Unexpected error while fetching training data")

    def _process_pair_batch(self, pairs):
        text_ids = {pid for p in pairs for pid in (p["left_id"], p["right_id"])}

        texts_cursor = self.original_collection.find(
            {"_id": {"$in": list(text_ids)}},
            {"text": 1},
        ).sort("_id", 1)

        text_map = {doc["_id"]: doc["text"] for doc in texts_cursor}

        for p in pairs:
            yield {
                "left_id": p["left_id"],
                "right_id": p["right_id"],
                "same": p["same"],
                "left_text": text_map.get(p["left_id"]),
                "right_text": text_map.get(p["right_id"]),
            }
