# kubectl apply -f mongodb-stud-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: insert-mongodb-stud
  namespace: webisservices
spec:
  template:
    spec:
      containers:
      - name: mongodb-stud
        image: registry.webis.de/code-teaching/theses/artificial-authorship-verification:latest
        command: ["bash", "/src/genai_detection/mongo_db/collection_orginal_text_student_essays.py"]
        volumeMounts:
        - name: src-volume
          mountPath: /src
      volumes:
      - name: src-volume
        hostPath:
          path: /mnt/ceph/storage/data-tmp/current/kgutekunst/dev/artificial-authorship-verification/
          type: Directory
      restartPolicy: Never
